### ISSUE TITLE
Make won't compile the documents.

### ISSUE THREAD

**Issue by joseedil** [forsyde/forsyde-atom#22]
There are missing commands on the forsyde-tikz style files:

\mapSG
\combinator

There are also /composite keys/ issues I could not find.

**Comment by ugeorge** [comment]
Yes, forsyde-tikz seems to go wrong with TexLive 2016... I will look into it when I have time.

**Comment by ugeorge** [comment]
For now I took out the documentation from the `master` branch, into `docs`, and I will keep it that way, as long as the Haddock generated page is available at [forsyde.github.io/forsyde-atom](forsyde.github.io/forsyde-atom). Thus `docs` wil be a developing branch, excluded from the CI flow. It will be updated once the new release of `forsyde-tikz` is available.
